language: php
php:
- 7.2
services:
- mysql
before_script:
- composer install
script: "./vendor/bin/phpunit ./tests"
deploy:
  provider: heroku
  app: sesion6-github
  on: master
  skip_cleanup: true
  api_key:
    secure: lrt8WFMWNI8AAXLu4u69CWt1CoyDthfuozXFlyhaVemt2uJQYGI7rbv5vkcwNFLWXFydciLBhqCVvb6xCXa7+pKX6J3+VbhWBNzfNTITj2zWpTWs374LQDXhbjhY0nbKn0Ddvd5jDLUAXr3WoIqbzSTCfivrErrufiR8HaHGfa/VLOmQPdJRM592+r0YoKSnXllQ6Jh/8htOuRX8jQD0CsYkFiOraxepmsiTDgvATJshtb4Si/jZEQp0HfFzaVdTeqkCJuG3pJGgXC6t6CVjGjhaUuqZ8paVrmfJTNFcA2FuMvOEaSMM5wWaIPhX9J6D6mAiERpE+t1CLjC1YwJvHqU0IrvYIvN7l07LYHL/fvyqEKC0OA8VL1UnDmOvDQToddQd81Xy4/Gm8zGdXzwgyAZH72rvcZjq8Q1v43F1vCaiJN0Z6SREimgCfWybDh3mUGPcIR5nfgQ0m8f4DrEQjTGLK9Nl2nvRxth0V8p9tAGuGs0QHtKax/mRNdkZ08D1iNQ9ytpWuSdodaP3hbhhcWBix4fVBbkWtJPbpJO0JhWEBQ0vnbaLhqUpNPwuDR4EahdTDY5vfMPxqtA5DS9wqsPEO5uHYO7I5cSCwcj+PaRATzKArYoLfZoCDrWWbVIv/UDpx2D3/5w1B7xnjkjNIE9FqId6n6Sf+JV4L+Q9kFY=
